# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            The Delta
tagline:          'A Jekyll theme'
description:      'A simple blog from a mathematically-inclined software engineer'
url:              http://jpbochicchio.github.io
baseurl:          /

author:
  name:           'John Bochicchio'
  url:            https://news.ycombinator.com/user?id=Affine_Stack

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jpbochicchio/jpbochicchio.github.io
