[package]
name = "rust-wasm-gh-pages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { version = "0.20.0", features = ["csr"]}
material-yew = "0.3.0"
yew-router = "0.17"